# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://in-sight.it'
baseurl: ''
title: 'IN-SIGHT.it'
description: 'Citizenship and standard-setting in digital networks'
permalink: pretty
# logo: "https://avatars.githubusercontent.com/u/75691025"
logo: "/assets/logos/logo.png"

favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  144: '/assets/logos/logo@144px.png'

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Team
  url: /team/
- title: Academic Board
  url: /academicboard/
- title: Valorization Board
  url: /valorizationboard/
- title: Publications
  url: /publications/
- title: Outreach
  url: /outreach/
- title: Waves of Interference 5G Lab
  url: /wavesofinterference/



# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

fonts:

  font_urls:
    - ../assets/fonts/SourceSans3-VariableFont_wght.woff2
