theme: jekyll-theme-slate
title: IN-SIGHT.it
description: An interdisciplinary academic project aimed at co-designing for public values in standards-making and governance

navbar-links:
  About: index.md
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"


# Personalize the colours in your website. Colour values can be any valid CSS colour

#navbar-col: "#EAEAEA"
#navbar-text-col: "#404040"
#navbar-border-col: "#DDDDDD"
#page-col: "#FFFFFF"
#text-col: "#404040"
#link-col: "#008AFF"
#hover-col: "#0085A1"
#footer-col: "#EAEAEA"
#footer-text-col: "#777777"
#footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

## This did not seem to work
# header_pages:
#   - index.md
#   - team.md
#   - academicboard.md
#   - valorizationboard.md
